## Imports

In [1]:
# instalar as dependências
!apt-get update -qq
!apt-get install openjdk-8-jdk-headless -qq > /dev/null
!wget -q https://archive.apache.org/dist/spark/spark-3.1.2/spark-3.1.2-bin-hadoop2.7.tgz
!tar xf spark-3.1.2-bin-hadoop2.7.tgz
!pip install -q findspark

In [2]:
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.1.2-bin-hadoop2.7"

In [3]:
import findspark
findspark.init()

In [4]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [5]:
from pyspark.sql import functions as F
from pyspark.sql.window import Window

# Carregamento de Dados
---

In [6]:
from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .master('local[*]') \
    .appName("Iniciando com Spark") \
    .getOrCreate()

In [7]:
spark

### Montando o drive

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### Carregando os dados dos Resultados

In [9]:
path = '/content/drive/MyDrive/resultados/SP_turno_1.csv'
resultados = spark.read.csv(path, sep=';', inferSchema=True, header=True, encoding='ISO-8859-1')

### Carregando os dados do Eleitorado

In [10]:
path = '/content/drive/MyDrive/eleitorado/perfil_eleitorado_2020/perfil_eleitorado_2020.csv'
eleitorado = spark.read.csv(path, sep=';', inferSchema=True, header=True, encoding='ISO-8859-1')

# Manipulando os Dados
---

## Operações básicas

In [13]:
resultados.limit(5).toPandas()

,DT_GERACAO,HH_GERACAO,ANO_ELEICAO,CD_TIPO_ELEICAO,NM_TIPO_ELEICAO,CD_PLEITO,DT_PLEITO,NR_TURNO,CD_ELEICAO,DS_ELEICAO,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO,NR_ZONA,NR_SECAO,NR_LOCAL_VOTACAO,CD_CARGO_PERGUNTA,DS_CARGO_PERGUNTA,NR_PARTIDO,SG_PARTIDO,NM_PARTIDO,DT_BU_RECEBIDO,QT_APTOS,QT_COMPARECIMENTO,QT_ABSTENCOES,CD_TIPO_URNA,DS_TIPO_URNA,CD_TIPO_VOTAVEL,DS_TIPO_VOTAVEL,NR_VOTAVEL,NM_VOTAVEL,QT_VOTOS,NR_URNA_EFETIVADA,CD_CARGA_1_URNA_EFETIVADA,CD_CARGA_2_URNA_EFETIVADA,CD_FLASHCARD_URNA_EFETIVADA,DT_CARGA_URNA_EFETIVADA,DS_CARGO_PERGUNTA_SECAO,DS_AGREGADAS,DT_ABERTURA,DT_ENCERRAMENTO,QT_ELEITORES_BIOMETRIA_NH,DT_EMISSAO_BU,NR_JUNTA_APURADORA,NR_TURMA_APURADORA
0,18/11/2020,15:49:53,2020,0,Eleição Ordinária,304,15/11/2020,1,426,Eleições Municipais 2020,SP,71072,SÃO PAULO,1,1,1015,11,Prefeito,-1,#NULO#,#NULO#,15/11/2020 22:26:42,386,241,145,1,APURADA,2,Branco,95,Branco,5,1618073,432.454.548.163.181.015.,306.728,E0BA7264,03/11/2020 11:19:00,11 - 1,#NULO#,15/11/2020 07:00:00,15/11/2020 17:02:46,0,15/11/2020 17:04:06,-1,-1
1,18/11/2020,15:49:53,2020,0,Eleição Ordinária,304,15/11/2020,1,426,Eleições Municipais 2020,SP,71072,SÃO PAULO,1,1,1015,11,Prefeito,13,PT,Partido dos Trabalhadores,15/11/2020 22:26:42,386,241,145,1,APURADA,1,Nominal,13,JILMAR TATTO,4,1618073,432.454.548.163.181.015.,306.728,E0BA7264,03/11/2020 11:19:00,11 - 1,#NULO#,15/11/2020 07:00:00,15/11/2020 17:02:46,0,15/11/2020 17:04:06,-1,-1
2,18/11/2020,15:49:53,2020,0,Eleição Ordinária,304,15/11/2020,1,426,Eleições Municipais 2020,SP,71072,SÃO PAULO,1,1,1015,11,Prefeito,18,REDE,Rede Sustentabilidade,15/11/2020 22:26:42,386,241,145,1,APURADA,1,Nominal,18,MARINA HELOU,1,1618073,432.454.548.163.181.015.,306.728,E0BA7264,03/11/2020 11:19:00,11 - 1,#NULO#,15/11/2020 07:00:00,15/11/2020 17:02:46,0,15/11/2020 17:04:06,-1,-1
3,18/11/2020,15:49:53,2020,0,Eleição Ordinária,304,15/11/2020,1,426,Eleições Municipais 2020,SP,71072,SÃO PAULO,1,1,1015,11,Prefeito,40,PSB,Partido Socialista Brasileiro,15/11/2020 22:26:42,386,241,145,1,APURADA,1,Nominal,40,MÁRCIO FRANÇA,29,1618073,432.454.548.163.181.015.,306.728,E0BA7264,03/11/2020 11:19:00,11 - 1,#NULO#,15/11/2020 07:00:00,15/11/2020 17:02:46,0,15/11/2020 17:04:06,-1,-1
4,18/11/2020,15:49:53,2020,0,Eleição Ordinária,304,15/11/2020,1,426,Eleições Municipais 2020,SP,71072,SÃO PAULO,1,1,1015,11,Prefeito,45,PSDB,Partido da Social Democracia Brasileira,15/11/2020 22:26:42,386,241,145,1,APURADA,1,Nominal,45,BRUNO COVAS,111,1618073,432.454.548.163.181.015.,306.728,E0BA7264,03/11/2020 11:19:00,11 - 1,#NULO#,15/11/2020 07:00:00,15/11/2020 17:02:46,0,15/11/2020 17:04:06,-1,-1

In [14]:
eleitorado.limit(5).toPandas()

,DT_GERACAO,HH_GERACAO,ANO_ELEICAO,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO,CD_MUN_SIT_BIOMETRIA,DS_MUN_SIT_BIOMETRIA,NR_ZONA,CD_GENERO,DS_GENERO,CD_ESTADO_CIVIL,DS_ESTADO_CIVIL,CD_FAIXA_ETARIA,DS_FAIXA_ETARIA,CD_GRAU_ESCOLARIDADE,DS_GRAU_ESCOLARIDADE,QT_ELEITORES_PERFIL,QT_ELEITORES_BIOMETRIA,QT_ELEITORES_DEFICIENCIA,QT_ELEITORES_INC_NM_SOCIAL
0,01/08/2020,08:37:48,2020,SP,70734,SÃO BENTO DO SAPUCAÍ,0,Sem biometria,314,4,FEMININO,3,CASADO,7074,70 a 74 anos,3,ENSINO FUNDAMENTAL INCOMPLETO,47,37,1,0
1,01/08/2020,08:37:48,2020,SP,70734,SÃO BENTO DO SAPUCAÍ,0,Sem biometria,314,4,FEMININO,3,CASADO,7074,70 a 74 anos,4,ENSINO FUNDAMENTAL COMPLETO,5,4,0,0
2,01/08/2020,08:37:48,2020,SP,70734,SÃO BENTO DO SAPUCAÍ,0,Sem biometria,314,4,FEMININO,3,CASADO,7074,70 a 74 anos,5,ENSINO MÉDIO INCOMPLETO,1,1,0,0
3,01/08/2020,08:37:48,2020,SP,70734,SÃO BENTO DO SAPUCAÍ,0,Sem biometria,314,4,FEMININO,3,CASADO,7074,70 a 74 anos,6,ENSINO MÉDIO COMPLETO,10,8,0,0
4,01/08/2020,08:37:48,2020,SP,70734,SÃO BENTO DO SAPUCAÍ,0,Sem biometria,314,4,FEMININO,3,CASADO,7074,70 a 74 anos,8,SUPERIOR COMPLETO,23,18,0,0

### Selecionando as colunas do DataFrame

In [11]:
resultados

DataFrame[DT_GERACAO: string, HH_GERACAO: string, ANO_ELEICAO: int, CD_TIPO_ELEICAO: int, NM_TIPO_ELEICAO: string, CD_PLEITO: int, DT_PLEITO: string, NR_TURNO: int, CD_ELEICAO: int, DS_ELEICAO: string, SG_UF: string, CD_MUNICIPIO: int, NM_MUNICIPIO: string, NR_ZONA: int, NR_SECAO: int, NR_LOCAL_VOTACAO: int, CD_CARGO_PERGUNTA: int, DS_CARGO_PERGUNTA: string, NR_PARTIDO: int, SG_PARTIDO: string, NM_PARTIDO: string, DT_BU_RECEBIDO: string, QT_APTOS: int, QT_COMPARECIMENTO: int, QT_ABSTENCOES: int, CD_TIPO_URNA: int, DS_TIPO_URNA: string, CD_TIPO_VOTAVEL: int, DS_TIPO_VOTAVEL: string, NR_VOTAVEL: int, NM_VOTAVEL: string, QT_VOTOS: int, NR_URNA_EFETIVADA: int, CD_CARGA_1_URNA_EFETIVADA: string, CD_CARGA_2_URNA_EFETIVADA: double, CD_FLASHCARD_URNA_EFETIVADA: string, DT_CARGA_URNA_EFETIVADA: string, DS_CARGO_PERGUNTA_SECAO: string, DS_AGREGADAS: string, DT_ABERTURA: string, DT_ENCERRAMENTO: string, QT_ELEITORES_BIOMETRIA_NH: int, DT_EMISSAO_BU: string, NR_JUNTA_APURADORA: int, NR_TURMA_APURADORA: int]

In [12]:
eleitorado

DataFrame[DT_GERACAO: string, HH_GERACAO: string, ANO_ELEICAO: int, SG_UF: string, CD_MUNICIPIO: int, NM_MUNICIPIO: string, CD_MUN_SIT_BIOMETRIA: int, DS_MUN_SIT_BIOMETRIA: string, NR_ZONA: int, CD_GENERO: int, DS_GENERO: string, CD_ESTADO_CIVIL: int, DS_ESTADO_CIVIL: string, CD_FAIXA_ETARIA: int, DS_FAIXA_ETARIA: string, CD_GRAU_ESCOLARIDADE: int, DS_GRAU_ESCOLARIDADE: string, QT_ELEITORES_PERFIL: int, QT_ELEITORES_BIOMETRIA: int, QT_ELEITORES_DEFICIENCIA: int, QT_ELEITORES_INC_NM_SOCIAL: int]

In [13]:
resultados = resultados.select("NM_MUNICIPIO", "NR_ZONA", "NR_SECAO", "DS_CARGO_PERGUNTA", "SG_PARTIDO", "QT_APTOS", "QT_COMPARECIMENTO", "QT_ABSTENCOES", "NM_VOTAVEL", "QT_VOTOS")

In [14]:
eleitorado = eleitorado.select("NM_MUNICIPIO", "NR_ZONA", "DS_GENERO", "DS_ESTADO_CIVIL", "DS_FAIXA_ETARIA", "DS_GRAU_ESCOLARIDADE", "QT_ELEITORES_PERFIL", "QT_ELEITORES_DEFICIENCIA", "QT_ELEITORES_INC_NM_SOCIAL")

## Encontrando o prefeito mais votado de cada cidade

In [128]:
# Aqui, estamos agrupando os resultados com base em múltiplas colunas:
# Para cada grupo, estamos somando os votos ("QT_VOTOS") e renomeando essa soma para "TOTAL_VOTOS".
candidato_mais_votado = resultados.groupBy("NM_MUNICIPIO", "NM_VOTAVEL", "DS_CARGO_PERGUNTA", "SG_PARTIDO").agg(F.sum("QT_VOTOS").alias("TOTAL_VOTOS"))

# Nesta linha, estamos filtrando apenas os registros onde o cargo em disputa é "Prefeito".
candidato_mais_votado_prefeito = candidato_mais_votado.filter(candidato_mais_votado["DS_CARGO_PERGUNTA"] == "Prefeito")

# Aqui, estamos definindo uma janela de análise (window) que particiona os dados pelo "NM_MUNICIPIO" (nome do município)
# e os ordena em ordem decrescente pelo "TOTAL_VOTOS" (quantidade de votos).
window_spec = Window.partitionBy("NM_MUNICIPIO").orderBy(F.desc("TOTAL_VOTOS"))

# Com base na janela definida acima, estamos adicionando uma nova coluna chamada "rank" ao DataFrame.
# Esta coluna "rank" representa o ranking de cada candidato a prefeito em seu respectivo município com base no número total de votos.
candidato_mais_votado_prefeito_ranked = candidato_mais_votado_prefeito.withColumn("rank", F.row_number().over(window_spec))

# Finalmente, filtramos apenas os candidatos que estão em 1º lugar no ranking (ou seja, os mais votados) em cada município.
candidato_mais_votado_in_each_municipio_prefeito = candidato_mais_votado_prefeito_ranked.filter(candidato_mais_votado_prefeito_ranked["rank"] == 1)

In [129]:
candidato_mais_votado_in_each_municipio_prefeito.toPandas()

,NM_MUNICIPIO,NM_VOTAVEL,DS_CARGO_PERGUNTA,SG_PARTIDO,TOTAL_VOTOS,rank
0,CANAS,SILVANA ZANIN,Prefeito,PDT,1108,1
1,PORTO FELIZ,DR CÁSSIO,Prefeito,PTB,25318,1
2,RIBEIRÃO BRANCO,MAURO TEIXEIRA,Prefeito,PP,5914,1
3,SÃO JOAQUIM DA BARRA,SCHMIDT,Prefeito,MDB,9789,1
4,ARCO-ÍRIS,ALDO MANSANO,Prefeito,PV,1134,1
...,...,...,...,...,...,...
640,SÃO SEBASTIÃO DA GRAMA,ZÉ DA DOCA,Prefeito,PTB,2402,1
641,NOVA CANAÃ PAULISTA,THAIS,Prefeito,PSDB,743,1
642,CAMPINA DO MONTE ALEGRE,ZE DITO,Prefeito,PSDB,2439,1
643,SÃO JOSÉ DO BARREIRO,LÊ BRAGA,Prefeito,PSDB,1570,1
644,ÁGUAS DA PRATA,REGINA,Prefeito,PSC,2211,1

## Buscando a porcentagem de votos que um candidato teve em cada zona e informações do perfil de eleitor predominante nela.

In [25]:
def votos_candidato_zona(nome_candidato, partido, df_votos, df_eleitorado):
    # 1. Filtrar o dataframe de votos pelo nome do candidato e partido
    df_candidato_votos = df_votos.filter((df_votos.NM_VOTAVEL == nome_candidato) & (df_votos.SG_PARTIDO == partido))

    # 2. Agrupar pelo NM_MUNICIPIO e NR_ZONA para somar a quantidade de votos por zona
    df_candidato_votos_agrupado = df_candidato_votos.groupBy("NM_MUNICIPIO", "NR_ZONA").agg(F.sum("QT_VOTOS").alias("TOTAL_VOTOS"))

    # 3. Ordenar as zonas pelo número de votos em ordem decrescente
    df_candidato_votos_agrupado = df_candidato_votos_agrupado.orderBy("TOTAL_VOTOS", ascending=False)

    # 4. Juntar o dataframe de eleitorado com o dataframe de votos agrupados usando o NM_MUNICIPIO e NR_ZONA
    df_joined = df_candidato_votos_agrupado.join(df_eleitorado, ["NM_MUNICIPIO", "NR_ZONA"])

    # Computa a soma dos perfis para cada categoria
    df_sum = df_joined.groupBy("NM_MUNICIPIO", "NR_ZONA", "DS_GENERO", "DS_FAIXA_ETARIA", "DS_GRAU_ESCOLARIDADE").agg(F.sum("QT_ELEITORES_PERFIL").alias("TOTAL_PERFIL"))

    # 5. Encontrar a moda das colunas de interesse
    window = Window.partitionBy("NM_MUNICIPIO", "NR_ZONA").orderBy(F.desc("TOTAL_PERFIL"))

    df_genero = df_sum.withColumn("rank", F.row_number().over(window)).filter("rank = 1").select("NM_MUNICIPIO", "NR_ZONA", "DS_GENERO").drop("rank")
    df_faixa = df_sum.withColumn("rank", F.row_number().over(window)).filter("rank = 1").select("NM_MUNICIPIO", "NR_ZONA", "DS_FAIXA_ETARIA").drop("rank")
    df_escolaridade = df_sum.withColumn("rank", F.row_number().over(window)).filter("rank = 1").select("NM_MUNICIPIO", "NR_ZONA", "DS_GRAU_ESCOLARIDADE").drop("rank")

    # Agregar o total de eleitores por NM_MUNICIPIO e NR_ZONA
    df_total_eleitores = df_eleitorado.groupBy("NM_MUNICIPIO", "NR_ZONA").agg(F.sum("QT_ELEITORES_PERFIL").alias("TOTAL_ELEITORES"))

    # Calcular a porcentagem de votos
    df_candidato_votos_agrupado = df_candidato_votos_agrupado.join(df_total_eleitores, ["NM_MUNICIPIO", "NR_ZONA"])
    df_candidato_votos_agrupado = df_candidato_votos_agrupado.withColumn("PERCENTUAL_VOTOS", F.round((F.col("TOTAL_VOTOS") / F.col("TOTAL_ELEITORES")) * 100, 2))
    # Junta os resultados
    df_result = df_candidato_votos_agrupado.join(df_genero, ["NM_MUNICIPIO", "NR_ZONA"]).join(df_faixa, ["NM_MUNICIPIO", "NR_ZONA"]).join(df_escolaridade, ["NM_MUNICIPIO", "NR_ZONA"])

    return df_result

In [26]:
result = votos_candidato_zona('MÁRCIO FRANÇA', 'PSB', resultados, eleitorado)
result_pandas = result.toPandas()

In [27]:
result_pandas

,NM_MUNICIPIO,NR_ZONA,TOTAL_VOTOS,TOTAL_ELEITORES,PERCENTUAL_VOTOS,DS_GENERO,DS_FAIXA_ETARIA,DS_GRAU_ESCOLARIDADE
0,SÃO PAULO,327,10028,116314,8.62,FEMININO,35 a 39 anos,ENSINO MÉDIO COMPLETO
1,SÃO PAULO,398,9382,99098,9.47,FEMININO,30 a 34 anos,ENSINO MÉDIO COMPLETO
2,SÃO PAULO,247,10695,107948,9.91,FEMININO,35 a 39 anos,ENSINO MÉDIO COMPLETO
3,SÃO PAULO,250,13242,165668,7.99,FEMININO,40 a 44 anos,SUPERIOR COMPLETO
4,SÃO PAULO,20,11779,157859,7.46,FEMININO,35 a 39 anos,ENSINO MÉDIO COMPLETO
5,SÃO PAULO,254,13830,153234,9.03,FEMININO,35 a 39 anos,ENSINO MÉDIO COMPLETO
6,SÃO PAULO,352,17419,203201,8.57,FEMININO,35 a 39 anos,ENSINO MÉDIO COMPLETO
7,SÃO PAULO,6,11604,159499,7.28,FEMININO,40 a 44 anos,SUPERIOR COMPLETO
8,SÃO PAULO,258,12276,185209,6.63,FEMININO,40 a 44 anos,SUPERIOR COMPLETO
9,SÃO PAULO,373,9895,128866,7.68,FEMININO,35 a 39 anos,ENSINO MÉDIO COMPLETO
10,SÃO PAULO,353,14688,176776,8.31,FEMININO,25 a 29 anos,ENSINO MÉDIO COMPLETO
11,SÃO PAULO,347,16379,171894,9.53,FEMININO,35 a 39 anos,ENSINO MÉDIO COMPLETO
12,SÃO PAULO,351,9320,130175,7.16,MASCULINO,25 a 29 anos,ENSINO MÉDIO INCOMPLETO
13,SÃO PAULO,413,13698,147599,9.28,FEMININO,35 a 39 anos,ENSINO MÉDIO COMPLETO
14,SÃO PAULO,253,19977,217744,9.17,FEMININO,35 a 39 anos,SUPERIOR COMPLETO
15,SÃO PAULO,404,16266,185463,8.77,FEMININO,25 a 29 anos,ENSINO MÉDIO COMPLETO
16,SÃO PAULO,421,11356,141625,8.02,FEMININO,35 a 39 anos,ENSINO MÉDIO COMPLETO
17,SÃO PAULO,372,20289,267732,7.58,FEMININO,35 a 39 anos,ENSINO MÉDIO COMPLETO
18,SÃO PAULO,348,8773,101362,8.66,FEMININO,35 a 39 anos,ENSINO MÉDIO COMPLETO
19,SÃO PAULO,422,13103,144498,9.07,FEMININO,35 a 39 anos,ENSINO MÉDIO COMPLETO
20,SÃO PAULO,325,8585,98797,8.69,FEMININO,35 a 39 anos,SUPERIOR COMPLETO
21,SÃO PAULO,349,11224,128493,8.74,FEMININO,35 a 39 anos,ENSINO MÉDIO COMPLETO
22,SÃO PAULO,3,6357,76654,8.29,FEMININO,35 a 39 anos,ENSINO MÉDIO COMPLETO
23,SÃO PAULO,280,12518,168405,7.43,FEMININO,35 a 39 anos,ENSINO MÉDIO COMPLETO
24,SÃO PAULO,371,12875,192416,6.69,FEMININO,35 a 39 anos,ENSINO MÉDIO COMPLETO
25,SÃO PAULO,374,16746,239937,6.98,FEMININO,35 a 39 anos,ENSINO MÉDIO COMPLETO
26,SÃO PAULO,252,10129,110946,9.13,FEMININO,35 a 39 anos,ENSINO MÉDIO COMPLETO
27,SÃO PAULO,1,10223,153345,6.67,FEMININO,35 a 39 anos,SUPERIOR COMPLETO
28,SÃO PAULO,249,10272,111823,9.19,FEMININO,55 a 59 anos,SUPERIOR COMPLETO
29,SÃO PAULO,259,11394,151795,7.51,FEMININO,40 a 44 anos,SUPERIOR COMPLETO
30,SÃO PAULO,326,8910,107402,8.30,FEMININO,35 a 39 anos,ENSINO MÉDIO COMPLETO
31,SÃO PAULO,403,9237,106146,8.70,FEMININO,35 a 39 anos,ENSINO MÉDIO COMPLETO
32,SÃO PAULO,251,6126,112494,5.45,FEMININO,60 a 64 anos,SUPERIOR COMPLETO
33,SÃO PAULO,260,15807,177883,8.89,FEMININO,35 a 39 anos,ENSINO MÉDIO COMPLETO
34,SÃO PAULO,418,13703,188592,7.27,FEMININO,35 a 39 anos,ENSINO MÉDIO COMPLETO
35,SÃO PAULO,255,16653,185970,8.95,FEMININO,35 a 39 anos,ENSINO MÉDIO COMPLETO
36,SÃO PAULO,420,10738,119980,8.95,FEMININO,35 a 39 anos,ENSINO MÉDIO COMPLETO
37,SÃO PAULO,397,14178,151848,9.34,FEMININO,25 a 29 anos,ENSINO MÉDIO COMPLETO
38,SÃO PAULO,4,13094,160277,8.17,FEMININO,40 a 44 anos,SUPERIOR COMPLETO
39,SÃO PAULO,2,11764,180604,6.51,FEMININO,35 a 39 anos,SUPERIOR COMPLETO
40,SÃO PAULO,381,15553,226781,6.86,FEMININO,30 a 34 anos,ENSINO MÉDIO COMPLETO
41,SÃO PAULO,376,20683,239886,8.62,FEMININO,30 a 34 anos,ENSINO MÉDIO COMPLETO
42,SÃO PAULO,417,11532,122743,9.40,FEMININO,35 a 39 anos,ENSINO MÉDIO COMPLETO
43,SÃO PAULO,256,16019,174812,9.16,FEMININO,25 a 29 anos,ENSINO MÉDIO COMPLETO
44,SÃO PAULO,392,12187,125899,9.68,FEMININO,35 a 39 anos,ENSINO MÉDIO COMPLETO
45,SÃO PAULO,405,9642,106302,9.07,FEMININO,35 a 39 anos,ENSINO MÉDIO COMPLETO
46,SÃO PAULO,390,10956,118335,9.26,FEMININO,35 a 39 anos,ENSINO MÉDIO COMPLETO
47,SÃO PAULO,389,15281,187780,8.14,FEMININO,25 a 29 anos,ENSINO MÉDIO COMPLETO
48,SÃO PAULO,328,13184,173477,7.60,FEMININO,35 a 39 anos,ENSINO MÉDIO COMPLETO
49,SÃO PAULO,246,7767,116359,6.68,FEMININO,40 a 44 anos,SUPERIOR COMPLETO
50,SÃO PAULO,320,14019,180691,7.76,FEMININO,35 a 39 anos,ENSINO MÉDIO COMPLETO
51,SÃO PAULO,248,13938,155101,8.99,FEMININO,35 a 39 anos,ENSINO MÉDIO COMPLETO
52,SÃO PAULO,408,11449,157950,7.25,FEMININO,35 a 39 anos,ENSINO MÉDIO COMPLETO
53,SÃO PAULO,257,13755,174997,7.86,FEMININO,35 a 39 anos,SUPERIOR COMPLETO
54,SÃO PAULO,375,20439,245862,8.31,FEMININO,35 a 39 anos,ENSINO MÉDIO COMPLETO
55,SÃO PAULO,346,9501,138199,6.87,FEMININO,40 a 44 anos,SUPERIOR COMPLETO
56,SÃO PAULO,5,6431,122204,5.26,FEMININO,60 a 64 anos,SUPERIOR COMPLETO
57,SÃO PAULO,350,11573,133738,8.65,FEMININO,35 a 39 anos,ENSINO MÉDIO COMPLETO

In [28]:
result_pandas.to_csv('ResultadosMFPSB2020.csv', sep=';', encoding='ISO-8859-1')

## Busca das zonas eleitorais com maior número de abstenções, votos brancos e nulos, indicando os locais com maior potencial para o candidato conquistar o eleitor indeciso.

In [156]:
df_brancos_nulos = resultados.filter(F.col('NM_VOTAVEL').isin(['BRANCO', 'NULO']))

# Agrupar por zona eleitoral e somar os votos e abstenções
df_agrupado = df_brancos_nulos.groupBy('NM_MUNICIPIO','NR_ZONA').agg(
    F.sum('QT_VOTOS').alias('TOTAL_VOTOS'),
    F.sum('QT_ABSTENCOES').alias('TOTAL_ABSTENCOES')
)

# Adicionar coluna total considerando votos brancos/nulos e abstenções
df_agrupado = df_agrupado.withColumn('TOTAL', F.col('TOTAL_VOTOS') + F.col('TOTAL_ABSTENCOES'))

# Ordenar por total em ordem decrescente e pegar as top 50 zonas
top_50_zonas = df_agrupado.sort(F.col('TOTAL').desc()).limit(50)

top_50_zonas.show()

+--------------------+-------+-----------+----------------+-----+
|        NM_MUNICIPIO|NR_ZONA|TOTAL_VOTOS|TOTAL_ABSTENCOES|TOTAL|
+--------------------+-------+-----------+----------------+-----+
|              OSASCO|    331|       1090|           24942|26032|
|         NOVA ODESSA|    292|        363|            9208| 9571|
|SÃO JOSÉ DO RIO P...|    124|        162|            9283| 9445|
|              OSASCO|    276|        103|            8928| 9031|
|           SÃO PEDRO|    130|        490|            8225| 8715|
|              OSASCO|    315|         53|            5465| 5518|
|              OSASCO|    213|         51|            4463| 4514|
|            CRUZEIRO|     42|         64|            3214| 3278|
|              OSASCO|    277|         24|            2897| 2921|
|                IEPÊ|    106|       1465|            1223| 2688|
|              OSASCO|    332|         25|            2582| 2607|
|              OCAUÇU|    180|        559|             469| 1028|
|               SALES|    207|        171|             828|  999|
|            ALAMBARI|     52|        195|             799|  994|
|         POTIRENDABA|    126|         13|             813|  826|
|          SERRA AZUL|    109|         18|             777|  795|
|            POPULINA|    233|        238|             545|  783|
|          CHARQUEADA|    244|          6|             289|  295|
+--------------------+-------+-----------+----------------+-----+